### ISSUE TITLE
Issue trying to create a temp file

### ISSUE THREAD

**Issue by rafaelfaria** [sindresorhus/tempy#14]
Tried to create a temp file using the command below:
```
const tmpAudioFilename = tempy.file({ extension: 'aac' });
```

Got the following error:
```
Error: ENOENT: no such file or directory, open '/private/var/folders/ql/zg2bpwbx64189d_bsbkqshqh0000gn/T/adb826c4bd78785c504a2e01cc52f474.aac'
```

Has anyone come across this issue? What did you do?

Mac OS Mojave
10.14.5

**Comment by LAMike310** [comment]
How did you solve this @rafaelfaria?

**Comment by scambier** [comment]
@LAMike310 I had the same issue, so I took a look at the source.

It turns out that `tempy.file()` does not create a file, it only generates a filename. If your want to create an empty, file you need to do this :
```js
const filePath = await tempy.write('', {extension:'txt'})
```
