### ISSUE TITLE
Properly removing leading dots

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/tempy#21]
I think the regex here:

https://github.com/sindresorhus/tempy/blob/a2c71980e1e2014dbf6a8e8eb6e445e2d99cb18c/index.js#L22

Should be replaced with:

```js
/^\.+/
```

Otherwise extensions like `..ext` will make this replacement useless, albeit maybe nobody ever passed an extension like that to this library.

**Comment by papb** [comment]
Arguably, if someone passes `..ext` as extension, wouldn't they want a result such as `foobar..ext`? This is the current behavior I think; with your change, `foobar.ext` would be generated instead, which would not be desired, right?

I think the purpose of this regexp is precisely to ignore the first dot if present (such that passing `ext` or `.ext` would yield the same result).

**Comment by fabiospampinato** [comment]
🤔 yeah I think you're right, thanks for the explanation.
