### ISSUE TITLE
Improve install size

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/tempy#27]
https://packagephobia.com/result?p=tempy

`tempy@0.7.0` install size is 1.61 MB

That's quite high. `0.6.0` was only 120KB.

**Comment by sindresorhus** [comment]
I agree, however, I have a plan. When the `recursive` option on `rmdir` is no longer experimental, we can use that one instead of `del`: https://nodejs.org/api/fs.html#fs_fs_rmdir_path_options_callback

---

Tip: You can use https://bundlephobia.com/result?p=tempy@0.7.0 to see what dependencies take up of the most space.

**Comment by sindresorhus** [comment]
I managed to improve it a little bit: https://packagephobia.com/result?p=tempy

**Comment by fregante** [comment]
> When the `recursive` option on `rmdir` is no longer experimental

You mean "when you want to target Node 12," I think. The option doesn't appear to be experimental.

**Comment by Richienb** [comment]
> When the `recursive` option on `rmdir` is no longer experimental

That's Node.js 12.10. Node.js will EOL in 1 month and 2 weeks.

**Comment by fregante** [comment]
Just in time for https://github.com/sindresorhus/meta/discussions/15!

**Comment by Richienb** [comment]
> I agree, however, I have a plan. When the recursive option on rmdir is no longer experimental, we can use that one instead of del: nodejs.org/api/fs.html#fs_fs_rmdir_path_options_callback

That option is deprecated now.

The alternative is [`fs.promises.rm`](https://nodejs.org/api/fs.html#fspromisesrmpath-options) in Node.js 14.14 which is 3 months away.

**Comment by Richienb** [comment]
> Side note: Could [`fs.mkdtemp`](https://nodejs.org/api/fs.html#fs_fs_mkdtempsync_prefix_options) be used to replace `unique-string`?

Yes it would, though we'd still need to use `unique-string` to generate the file since that isn't a feature yet
