### ISSUE TITLE
tempy.root doesn't do anything

### ISSUE THREAD

**Issue by SecretAgentKen** [sindresorhus/tempy#3]
Setting .root doesn't actually change where the temp directory is created since `getPath` never references it.

```javascript
var tempy = requite('tempy');
tempy.root = '/home/someuser';
console.log(tempy.directory());
```

Returns /tmp/somehash

**Comment by sindresorhus** [comment]
That's intentional. It's only for getting the root path. I've made that clear in the readme now.
