### ISSUE TITLE
Where did you find that OS will cleanup tmp dir?

### ISSUE THREAD

**Issue by gugu** [sindresorhus/tempy#4]
> The operating system will clean up when needed. No point in us wasting resources and adding complexity.

1. Most linux distros cleanup tmp on reboot. But if system does not make reboot, tmp is not cleared
2. Docker has no ability to run periodic cleanup script at all

Here is the example:

```
tmpfs            10M     0   10M   0% /home/gugu/test
gugu@container:~/test$ fallocate -l 1M t1
gugu@container:~/test$ fallocate -l 1M t2
gugu@container:~/test$ fallocate -l 1M t3
gugu@container:~/test$ fallocate -l 1M t4
gugu@container:~/test$ fallocate -l 1M t5
gugu@container:~/test$ fallocate -l 1M t6
gugu@container:~/test$ fallocate -l 1M t7
gugu@container:~/test$ fallocate -l 1M t8
gugu@container:~/test$ fallocate -l 1M t9
gugu@container:~/test$ fallocate -l 1M t10
gugu@container:~/test$ fallocate -l 1M t11
fallocate: fallocate failed: No space left on device
gugu@container:~/test$
```

**Comment by sindresorhus** [comment]
macOS: https://superuser.com/a/187105/6877

**Comment by gugu** [comment]
Probably it is better to replace:

> The operating system will clean up when needed. No point in us wasting resources and adding complexity.

with:

> macOS will clean up when needed. No point in us wasting resources and adding complexity.

**Comment by deevus** [comment]
I'm using `tempy` in AWS Lambda and it's quite useful. However I have to clean up after myself manually, since the storage in Lambda is only 512MB and can get used up quite quickly with subsequent invocations of the same execution context. 

It would be nice to have a cleanup method.
