### ISSUE TITLE
Prefixing the temp directory

### ISSUE THREAD

**Issue by compulim** [sindresorhus/tempy#5]
Options to prefix a temp directory for easier cleanup afterward. The prefix could include `/`.

**Comment by sindresorhus** [comment]
How does it ease cleanup? The created path is returned to you, so I don't see how this option would make it any easier to clean up.

**Comment by compulim** [comment]
Developers who use this package did not clean up properly (and some of them generate huge files). So as a user (me), I need to dig into my temp folder to clean them up.

Will be great to see if `tempy` can support prefix, or auto-generate a prefix based on timestamp the package is loaded. So at least, it's much easier for the user to clean up the mess a poor utility spit out.

**Comment by sindresorhus** [comment]
I'm gonna add cleanup methods instead => #11.
